logging:
  config: 'classpath:log4j2.yml'

spring:
  application:
    name: bludce-api
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://bludce_db:5432/${DB_NAME}  # docker-compose
#    url: jdbc:postgresql://localhost:5700/${DB_NAME}   # idea
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: bludce_redis     # docker-compose
      port: 6379
#      host: localhost     # idea
#      port: 6700
  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 10000   # 10 сек
            readTimeout: 60000  # 1 мин
            logger-level: full

app:
  auth:
    admin-code: ${ADMIN_CODE}
    password-life-time: ${PASSWORD_LIFE_TIME}
    token:
      access-life-time: ${ACCESS_LIFE_TIME}
      refresh-life-time: ${REFRESH_LIFE_TIME}
      secret: ${SECRET}
  ocr:
    api-key: ${OCR_KEY}
    url: ${OCR_URL}
  gigachat:
    auth-key: ${GIGACHAT_KEY}

server:
  port: 7200
